url: https://powderhouse.org
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
        - "design/index.html"

timezone: America/New_York
exclude: [node_modules, Gemfile, Gemfile.lock, .gitignore, package.json, README.md, CNAME, vendor]
gems:
  - jekyll-srcset
  - jekyll-autoprefixer
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"