meta:
  version: 0.6.2

plugins:
  - algoliasearch-jekyll
  - jekyll-sitemap
  - jekyll-autoprefixer

include: ["_headers", "_redirects"]
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]

algolia:
  application_id: 'NURLHE71FW'
  index_name: 'prod_powderhouse.org'
  record_css_selector: 'p,li,dt,dd'
  excluded_files:
    - 2015-01-01-post.md
  settings:
    allowTyposOnNumericTokens: false
    typoTolerance: false