url: https://powderhouse.org
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
        - "design/index.html"

timezone: America/New_York
exclude: [Gemfile, Gemfile.lock, .gitignore, package.json, README.md, CNAME, vendor]
gems:
  - jekyll-srcset
  - jekyll-assets
  - jekyll-tidy
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# Site variables
enrollEmail: "enroll@powderhouse.org"
smsNumber: "617-284-6004"